#!/usr/bin/env node

var post_gist = require("./lib/post")
  , program = require("commander")
  , exec = require('child_process').spawn
  , temp = require("temp")

program
  .version("0.0.0")
  .usage("[options] <file1, file2>")
  .option("-p, --public", "Make a public gist on your account (It's secret by default). Needs to read your authentication details from `git credential fill`.")
  .option("-a, --anonymous", "Make an anonymous gist")
  .option('-d, --description <string>', "A description for your gist", String)
  .option("-o, --open", "open the url in the default browser after creation")

program.parse(process.argv)

var privacy = ["anonymous", "public", "secret"]
  .filter(function(d, i, arr){
    privacy = arr[i]
    if (arr[i] == "secret"){
      return true
    }
    return program[d]
  })[0]

console.log(privacy)


post_gist(program.args, privacy, process.description, program.open)
